// <auto-generated />
using System;
using LinearUpdateDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinearUpdateDashboard.Data.Migrations
{
    [DbContext(typeof(LinearDbContext))]
    [Migration("20220714212324_AddDistributionServerLastSuccessfulDatabaseJob")]
    partial class AddDistributionServerLastSuccessfulDatabaseJob
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HeadquartersMarket", b =>
                {
                    b.Property<int>("HeadquartersId")
                        .HasColumnType("int");

                    b.Property<int>("MarketsId")
                        .HasColumnType("int");

                    b.HasKey("HeadquartersId", "MarketsId");

                    b.HasIndex("MarketsId");

                    b.ToTable("HeadquartersMarket");
                });

            modelBuilder.Entity("LinearUpdateDashboard.Models.DistributionServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("HeadquartersId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSuccessfulDatabaseJob")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServerFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HeadquartersId");

                    b.ToTable("DistributionServers");
                });

            modelBuilder.Entity("LinearUpdateDashboard.Models.DistributionServerSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DistributionServerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstAirDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SpotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistributionServerId");

                    b.HasIndex("SpotId");

                    b.ToTable("DistributionServerSpots");
                });

            modelBuilder.Entity("LinearUpdateDashboard.Models.Headquarters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Headquarters");
                });

            modelBuilder.Entity("LinearUpdateDashboard.Models.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("LinearUpdateDashboard.Models.Spot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spots");
                });

            modelBuilder.Entity("HeadquartersMarket", b =>
                {
                    b.HasOne("LinearUpdateDashboard.Models.Headquarters", null)
                        .WithMany()
                        .HasForeignKey("HeadquartersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinearUpdateDashboard.Models.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinearUpdateDashboard.Models.DistributionServer", b =>
                {
                    b.HasOne("LinearUpdateDashboard.Models.Headquarters", "Headquarters")
                        .WithMany("DistributionServers")
                        .HasForeignKey("HeadquartersId");

                    b.Navigation("Headquarters");
                });

            modelBuilder.Entity("LinearUpdateDashboard.Models.DistributionServerSpot", b =>
                {
                    b.HasOne("LinearUpdateDashboard.Models.DistributionServer", "DistributionServer")
                        .WithMany("DistributionServerSpots")
                        .HasForeignKey("DistributionServerId");

                    b.HasOne("LinearUpdateDashboard.Models.Spot", "Spot")
                        .WithMany("DistributionServerSpots")
                        .HasForeignKey("SpotId");

                    b.Navigation("DistributionServer");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("LinearUpdateDashboard.Models.DistributionServer", b =>
                {
                    b.Navigation("DistributionServerSpots");
                });

            modelBuilder.Entity("LinearUpdateDashboard.Models.Headquarters", b =>
                {
                    b.Navigation("DistributionServers");
                });

            modelBuilder.Entity("LinearUpdateDashboard.Models.Spot", b =>
                {
                    b.Navigation("DistributionServerSpots");
                });
#pragma warning restore 612, 618
        }
    }
}
